<x-filament-panels::page>
<style>
.fi-sidebar,.fi-topbar,#wai-sidebar-toggle{display:none!important}.fi-main{margin-inline-start:0!important;padding:0!important;background:#07111f!important}.fi-main-ctn{padding-top:0!important}.fi-page-header{display:none!important}.fi-page{padding:0!important}.fi-body{background:#07111f!important}
.team-shell{min-height:100vh;background:radial-gradient(circle at 12% 0,rgba(37,99,235,.18),transparent 28%),radial-gradient(circle at 92% 0,rgba(14,165,233,.12),transparent 22%),linear-gradient(180deg,#06101d,#081522 45%,#091522);color:#eef7ff;padding:20px}.team-wrap{max-width:1500px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.brand{display:flex;align-items:center;gap:12px}.logo{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;font-size:14px;font-weight:950;background:linear-gradient(135deg,#2563eb,#06b6d4);box-shadow:0 14px 34px rgba(37,99,235,.3)}.brand b{display:block;font-size:15px}.brand span{display:block;color:#8ba5bd;font-size:11px;margin-top:2px}.nav{display:flex;gap:8px;flex-wrap:wrap}.nav a{padding:10px 13px;border:1px solid #26394f;border-radius:12px;background:#0c1a2a;color:#a7bdd2;text-decoration:none;font-size:11px;font-weight:900}.nav a.active{color:#fff;border-color:transparent;background:linear-gradient(135deg,#2563eb,#0891b2)}
.hero{padding:28px;border-radius:28px;border:1px solid rgba(148,163,184,.12);background:linear-gradient(145deg,rgba(15,29,49,.98),rgba(7,17,31,.98));box-shadow:0 24px 70px rgba(0,0,0,.22)}.eyebrow{font-size:10px;letter-spacing:.17em;text-transform:uppercase;color:#78ddf7;font-weight:950}.hero h1{margin:8px 0 12px;font-size:clamp(34px,4.5vw,60px);line-height:1;letter-spacing:-.05em}.hero p{margin:0;max-width:900px;color:#b8c9d9;font-size:14px;line-height:1.72}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px}.kpi{padding:17px;border:1px solid #233448;background:linear-gradient(145deg,#0d1a2a,#0a1624);border-radius:17px}.kpi small{display:block;color:#8ba0b5;font-size:10px;font-weight:850}.kpi strong{display:block;margin-top:7px;font-size:30px;line-height:1;font-weight:950}.kpi em{display:block;margin-top:7px;color:#6c8399;font-size:9px;font-style:normal}.panel{margin-top:14px;border:1px solid #223348;background:rgba(11,23,39,.97);border-radius:21px;overflow:hidden}.panel-head{padding:17px 18px;border-bottom:1px solid rgba(148,163,184,.1)}.panel-head h2{margin:0;font-size:16px;font-weight:950}.panel-head p{margin:5px 0 0;color:#8399ae;font-size:10px;line-height:1.55}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:14px}.member{padding:15px;border:1px solid #24374c;border-radius:15px;background:#0b1827}.avatar{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;font-weight:950;background:#122841;color:#7eddf5}.member h3{margin:11px 0 3px;font-size:13px}.member p{margin:0;color:#7f95ab;font-size:9px}.stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.stat{padding:10px;border-radius:11px;background:#081420;border:1px solid #223449}.stat small{display:block;color:#7890a6;font-size:8px;text-transform:uppercase;font-weight:900}.stat b{display:block;margin-top:4px;font-size:16px}.empty{padding:45px 20px;text-align:center;color:#7e95aa;font-size:11px}.note{margin-top:12px;padding:13px 14px;border-radius:13px;border:1px solid rgba(56,189,248,.18);background:rgba(14,165,233,.06);color:#a9dced;font-size:10px;line-height:1.6}
@media(max-width:1000px){.grid{grid-template-columns:1fr 1fr}.kpis{grid-template-columns:1fr 1fr}}@media(max-width:650px){.team-shell{padding:11px}.top{align-items:flex-start;flex-direction:column}.nav{width:100%;display:grid;grid-template-columns:1fr 1fr 1fr}.nav a{text-align:center}.hero{padding:19px;border-radius:21px}.hero h1{font-size:34px}.grid{grid-template-columns:1fr}.kpis{grid-template-columns:1fr 1fr}}
</style>
@php($summary=$this->summary)
@php($members=$this->members)
<div class="team-shell"><div class="team-wrap">
@include('filament.partials.insurance-navigation', ['active' => 'team'])
<section class="hero"><div class="eyebrow">24/7 Operasyon Kontrolü</div><h1>Ekip yükünü tek merkezden yönetin.</h1><p>Aktif dosyaları, günlük poliçeleştirmeyi ve atanmamış işleri personel bazında görün. Sistem büyüdükçe operasyon dağılımı ve personel performansı bu merkezden yönetilecek.</p></section>
<section class="kpis"><article class="kpi"><small>Aktif Ekip</small><strong>{{ $summary['members'] }}</strong><em>Yetkili kullanıcı</em></article><article class="kpi"><small>Aktif Dosya</small><strong>{{ $summary['active_cases'] }}</strong><em>Ekip üzerinde</em></article><article class="kpi"><small>Bugün Poliçelendi</small><strong>{{ $summary['issued_today'] }}</strong><em>Günlük kapanış</em></article><article class="kpi"><small>Atanmamış İş</small><strong>{{ $summary['unassigned'] }}</strong><em>Dağıtım bekliyor</em></article></section>
<section class="panel"><div class="panel-head"><h2>Operasyon Ekibi</h2><p>Her personelin anlık iş yükünü ve günlük kapanışını izleyin.</p></div>
@if($members->isEmpty())<div class="empty">Henüz organizasyona bağlı ekip üyesi görünmüyor.</div>@else<div class="grid">@foreach($members as $member)<article class="member"><div class="avatar">{{ strtoupper(mb_substr($member['name'],0,2)) }}</div><h3>{{ $member['name'] }}</h3><p>{{ $member['email'] }}</p><div class="stats"><div class="stat"><small>Aktif Dosya</small><b>{{ $member['active_cases'] }}</b></div><div class="stat"><small>Bugün Poliçe</small><b>{{ $member['issued_today'] }}</b></div></div></article>@endforeach</div>@endif</section>
<div class="note">Dosya atamaları Operasyon ekranından yapılır ve işlem geçmişine kaydedilir. Bu merkez yalnız TPC organizasyonundaki aktif personelin güncel iş yükünü ve poliçe kapanışlarını gösterir.</div>
</div></div>
</x-filament-panels::page>
