<x-filament-panels::page>
<style>
.fi-sidebar,.fi-topbar,#wai-sidebar-toggle{display:none!important}.fi-main{margin-inline-start:0!important;padding:0!important;background:#07111f!important}.fi-main-ctn{padding-top:0!important}.fi-page-header{display:none!important}.fi-page{padding:0!important}.fi-body{background:#07111f!important}.fi-simple-main-ctn{padding:0!important}
.tpc-shell{min-height:100vh;background:radial-gradient(circle at 10% 0,rgba(37,99,235,.18),transparent 28%),radial-gradient(circle at 92% 0,rgba(14,165,233,.14),transparent 22%),linear-gradient(180deg,#06101d,#081522 42%,#091522);color:#eef7ff;padding:20px}.tpc-wrap{max-width:1560px;margin:auto}.tpc-top{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.tpc-brand{display:flex;align-items:center;gap:12px}.tpc-logo{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;font-size:16px;font-weight:950;background:linear-gradient(135deg,#2563eb,#06b6d4);box-shadow:0 14px 34px rgba(37,99,235,.3)}.tpc-brand b{display:block;font-size:15px}.tpc-brand span{display:block;color:#8ba5bd;font-size:11px;margin-top:2px}.tpc-nav{display:flex;gap:8px}.tpc-nav a{padding:10px 13px;border:1px solid #26394f;border-radius:12px;background:#0c1a2a;color:#a7bdd2;text-decoration:none;font-size:11px;font-weight:900}.tpc-nav a.active{color:#fff;border-color:transparent;background:linear-gradient(135deg,#2563eb,#0891b2);box-shadow:0 10px 26px rgba(37,99,235,.22)}
.tpc-launchpad{margin-bottom:14px;padding:18px;border:1px solid rgba(125,211,252,.13);border-radius:22px;background:linear-gradient(145deg,rgba(12,27,46,.98),rgba(7,18,31,.98));box-shadow:0 18px 50px rgba(0,0,0,.18)}.tpc-launch-head{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:14px}.tpc-launch-head span{color:#69d7f3;font-size:8px;font-weight:950;letter-spacing:.18em}.tpc-launch-head h2{margin:5px 0 0;font-size:20px;letter-spacing:-.03em}.tpc-launch-head p{max-width:510px;margin:0;color:#7891a8;font-size:9px;line-height:1.55}.tpc-module-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px}.tpc-module-card{position:relative;display:grid;grid-template-columns:auto 1fr;gap:10px;min-height:112px;padding:14px;border:1px solid #24384d;border-radius:16px;color:#d9e8f5;background:#091727;text-decoration:none;transition:.18s ease}.tpc-module-card:hover{transform:translateY(-2px);border-color:#3a5b78;box-shadow:0 13px 28px rgba(0,0,0,.16)}.tpc-module-card.active{border-color:rgba(56,189,248,.42);background:linear-gradient(145deg,rgba(37,99,235,.24),rgba(8,145,178,.12))}.tpc-module-card.payment{border-color:rgba(16,185,129,.24)}.tpc-module-card i{width:30px;height:30px;border-radius:10px;display:grid;place-items:center;color:#6dddf6;background:#142a42;font-size:8px;font-style:normal;font-weight:950}.tpc-module-card b{display:block;font-size:10px}.tpc-module-card span{display:block;margin-top:5px;color:#718aa1;font-size:8px;line-height:1.45}.tpc-module-card strong,.tpc-module-card em{position:absolute;right:13px;bottom:11px;color:#fff;font-size:18px;font-style:normal;font-weight:950}.tpc-module-card em{color:#6fdaf2;font-size:8px;letter-spacing:.08em}
.hero{display:grid;grid-template-columns:1.25fr .75fr;gap:16px;padding:28px;border-radius:28px;border:1px solid rgba(148,163,184,.12);background:linear-gradient(145deg,rgba(15,29,49,.98),rgba(7,17,31,.98));box-shadow:0 24px 70px rgba(0,0,0,.22)}.eyebrow{font-size:10px;letter-spacing:.17em;text-transform:uppercase;color:#78ddf7;font-weight:950}.hero h1{margin:8px 0 12px;font-size:clamp(36px,4.7vw,64px);line-height:.98;letter-spacing:-.05em}.hero p{margin:0;max-width:900px;color:#b8c9d9;font-size:14px;line-height:1.72}.hero-badges{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.badge{display:inline-flex;align-items:center;gap:7px;padding:8px 10px;border-radius:999px;border:1px solid;font-size:9px;font-weight:950}.badge.ok{background:rgba(16,185,129,.09);border-color:rgba(16,185,129,.24);color:#9be8c8}.badge.wait{background:rgba(245,158,11,.09);border-color:rgba(245,158,11,.23);color:#fbe2a0}.flow{display:grid;gap:8px;align-content:center}.flow-step{display:flex;align-items:center;gap:10px;padding:12px 13px;border:1px solid #293b50;background:rgba(6,16,29,.75);border-radius:14px}.flow-step i{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#14253a;color:#72dbf5;font-style:normal;font-size:10px;font-weight:950}.flow-step b{font-size:11px}.flow-step span{display:block;margin-top:2px;color:#8097ad;font-size:9px}
.kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-top:14px}.kpi{padding:16px;border:1px solid #233448;background:linear-gradient(145deg,#0d1a2a,#0a1624);border-radius:17px;box-shadow:0 13px 30px rgba(0,0,0,.13)}.kpi small{display:block;color:#8ba0b5;font-size:10px;font-weight:850}.kpi strong{display:block;margin-top:7px;font-size:28px;line-height:1;font-weight:950}.kpi em{display:block;margin-top:7px;color:#6c8399;font-size:9px;font-style:normal}
.workspace{display:grid;grid-template-columns:350px 1fr;gap:14px;margin-top:14px;align-items:start}.panel{border:1px solid #223348;background:rgba(11,23,39,.97);border-radius:21px;overflow:hidden;box-shadow:0 16px 42px rgba(0,0,0,.16)}.panel-head{padding:17px 18px;border-bottom:1px solid rgba(148,163,184,.1)}.panel-head h2{margin:0;font-size:16px;font-weight:950}.panel-head p{margin:5px 0 0;color:#8399ae;font-size:10px;line-height:1.55}.form{padding:16px;display:grid;gap:10px}.field label{display:block;margin-bottom:5px;color:#9db1c4;font-size:10px;font-weight:850}.input,.select{width:100%;padding:11px 12px;border-radius:11px;border:1px solid #304359;background:#081522;color:#f4f8fc;font-size:12px;outline:none}.input:focus,.select:focus{border-color:#22c7e8;box-shadow:0 0 0 3px rgba(34,199,232,.1)}.row2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.btn{border:0;border-radius:11px;padding:11px 12px;font-size:11px;font-weight:900;cursor:pointer}.btn.primary{color:#fff;background:linear-gradient(135deg,#2563eb,#0891b2);box-shadow:0 10px 24px rgba(37,99,235,.19)}.note{padding:11px 12px;border-radius:12px;border:1px solid rgba(56,189,248,.18);background:rgba(14,165,233,.06);color:#a9dced;font-size:9px;line-height:1.55}
.toolbar{display:flex;gap:7px;flex-wrap:wrap;padding:13px 14px;border-bottom:1px solid rgba(148,163,184,.1)}.toolbar .input{max-width:300px}.filters{display:flex;gap:6px;flex-wrap:wrap}.filters button{padding:8px 9px;border-radius:999px;border:1px solid #304359;background:#081522;color:#9fb2c5;font-size:9px;font-weight:850;cursor:pointer}.filters button.active{color:#fff;background:#11364c;border-color:#2383a0}.cards{display:grid;gap:9px;padding:12px}.case{display:grid;grid-template-columns:minmax(230px,1.2fr) minmax(190px,.9fr) minmax(130px,.55fr) minmax(120px,.55fr) auto;gap:12px;align-items:center;padding:14px;border:1px solid #23364b;border-radius:15px;background:linear-gradient(145deg,#0b1827,#0a1522);transition:.16s}.case:hover{border-color:#31506d;transform:translateY(-1px)}.case b{display:block;color:#f6f9fc;font-size:11px}.case span{display:block;color:#7e95aa;font-size:9px;margin-top:3px}.status{display:inline-flex!important;width:max-content;padding:6px 8px;border-radius:999px;font-size:8px!important;font-weight:950;background:#203247;color:#c7d6e4!important}.status.pending{background:rgba(245,158,11,.13);color:#f9d78c!important}.status.quoted{background:rgba(16,185,129,.13);color:#99e6c5!important}.status.attn{background:rgba(239,68,68,.13);color:#f8aaaa!important}.price{font-size:16px;font-weight:950;color:#fff}.case-actions{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.case-actions button,.case-actions a{padding:8px 9px;border-radius:9px;border:1px solid #30465f;background:#0b1928;color:#c9d9e8;font-size:8px;font-weight:900;cursor:pointer}.case-actions button.primary{background:linear-gradient(135deg,#2563eb,#0891b2);border-color:transparent;color:#fff}.empty{padding:44px 20px;text-align:center;color:#7e95aa;font-size:11px}
.detail-overlay{position:fixed;inset:0;z-index:999999;background:rgba(2,8,15,.72);backdrop-filter:blur(5px);display:flex;justify-content:flex-end}.drawer{width:min(620px,96vw);height:100%;overflow:auto;background:linear-gradient(180deg,#0a1625,#08131f);border-left:1px solid #2a3e54;box-shadow:-24px 0 70px rgba(0,0,0,.4);padding:20px}.drawer-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.drawer-top h2{margin:3px 0 4px;font-size:25px;letter-spacing:-.03em}.drawer-top p{margin:0;color:#8298ad;font-size:10px}.close{width:36px;height:36px;border-radius:11px;border:1px solid #30445b;background:#0e1c2d;color:#fff;cursor:pointer;font-size:18px}.progress{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:18px}.progress-step{padding:10px;border:1px solid #2b3d52;border-radius:12px;background:#0b1827}.progress-step small{display:block;color:#7c93a9;font-size:8px;font-weight:900;text-transform:uppercase}.progress-step b{display:block;margin-top:5px;font-size:9px}.progress-step.done{border-color:rgba(16,185,129,.35);background:rgba(16,185,129,.07)}.section{margin-top:14px;padding:15px;border:1px solid #24374c;border-radius:15px;background:#0b1827}.section h3{margin:0 0 11px;font-size:12px}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.info{padding:10px;border-radius:11px;background:#081420;border:1px solid #223449}.info small{display:block;color:#7890a6;font-size:8px;text-transform:uppercase;font-weight:900}.info b{display:block;margin-top:4px;font-size:10px}.quote-grid{display:grid;gap:8px}.quote{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px;border:1px solid #283c53;border-radius:12px;background:#091521}.quote.best{border-color:rgba(16,185,129,.38);background:rgba(16,185,129,.06)}.quote b{font-size:10px}.quote span{display:block;color:#7d94aa;font-size:8px;margin-top:2px}.quote strong{font-size:18px}.timeline{display:grid;gap:8px}.event{display:grid;grid-template-columns:8px 1fr;gap:9px}.event i{width:8px;height:8px;border-radius:50%;background:#22c7e8;margin-top:4px;box-shadow:0 0 0 4px rgba(34,199,232,.08)}.event b{font-size:9px}.event span{display:block;margin-top:2px;color:#7890a6;font-size:8px;line-height:1.5}.drawer-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.drawer-actions button,.drawer-actions a{padding:10px 12px;border-radius:10px;border:1px solid #30465f;background:#0c1a2a;color:#d2e1ee;font-size:9px;font-weight:900;cursor:pointer}.drawer-actions .primary{color:#fff;border:0;background:linear-gradient(135deg,#2563eb,#0891b2)}.drawer-actions button.success{color:#fff;border:0;background:linear-gradient(135deg,#059669,#0f766e)}
@media(max-width:1180px){.tpc-module-grid{grid-template-columns:repeat(2,1fr)}.tpc-module-card:last-child{grid-column:1/-1}.kpis{grid-template-columns:repeat(3,1fr)}.hero{grid-template-columns:1fr}.workspace{grid-template-columns:1fr}.case{grid-template-columns:1fr 1fr}.case-actions{justify-content:flex-start}}@media(max-width:700px){.tpc-launch-head{display:block}.tpc-launch-head p{margin-top:9px}.tpc-module-grid{grid-template-columns:1fr}.tpc-module-card:last-child{grid-column:auto}.tpc-shell{padding:11px}.tpc-top{align-items:flex-start;flex-direction:column}.tpc-nav{width:100%;display:grid;grid-template-columns:1fr 1fr}.tpc-nav a{text-align:center}.hero{padding:19px;border-radius:21px}.hero h1{font-size:35px}.flow{grid-template-columns:1fr 1fr}.kpis{grid-template-columns:1fr 1fr}.workspace{grid-template-columns:1fr}.row2{grid-template-columns:1fr}.toolbar .input{max-width:none}.case{grid-template-columns:1fr}.case-actions{justify-content:flex-start}.progress{grid-template-columns:1fr 1fr}.info-grid{grid-template-columns:1fr}}
</style>

@php($summary=$this->summary)
@php($open=$this->openStatus)
@php($cases=$this->cases)
@php($selected=$this->selectedCase)
<div class="tpc-shell"><div class="tpc-wrap">
@include('filament.partials.insurance-navigation', ['active' => 'operation'])
<section class="tpc-launchpad">
    <div class="tpc-launch-head">
        <div><span>ÜRÜN MERKEZİ</span><h2>Sigorta operasyonunun tamamı tek ekranda.</h2></div>
        <p>Bir bölüme geçmek için kartı seçin. Tüm modüller Doğuş Topçu Sigorta organizasyonuna özel çalışır.</p>
    </div>
    <div class="tpc-module-grid">
        <a class="tpc-module-card active" href="/admin/sigorta-operasyon"><i>01</i><div><b>Operasyon</b><span>Ruhsat, araç bilgileri ve canlı dosya kuyruğu</span></div><strong>{{ $summary['active'] }}</strong></a>
        <a class="tpc-module-card" href="/admin/sigorta-yenileme"><i>02</i><div><b>Geri Kazanım</b><span>Yenileme takibi ve kaybedilen müşteri operasyonu</span></div><em>GİT →</em></a>
        <a class="tpc-module-card" href="/admin/sigorta-ekip"><i>03</i><div><b>Ekip Merkezi</b><span>Personel iş yükü, atamalar ve günlük performans</span></div><em>GİT →</em></a>
        <a class="tpc-module-card" href="/admin/sigorta-yonetici"><i>04</i><div><b>Yönetici</b><span>KPI, dönüşüm ve operasyon kontrol paneli</span></div><em>GİT →</em></a>
        <a class="tpc-module-card payment" href="/admin/sigorta-teklif-odeme"><i>05</i><div><b>Teklif & Ödeme</b><span>Prim seçimi, ödeme kaydı ve poliçe kapanışı</span></div><strong>{{ $summary['quoted'] + $summary['payment'] }}</strong></a>
    </div>
</section>
<section class="hero"><div><div class="eyebrow">Canlı Sigorta Operasyonu</div><h1>Ruhsattan poliçeye tek akış.</h1><p>WhatsApp'tan gelen ruhsatı işleyin, araç bilgisini tek dosyada toplayın, Open teklif sonucunu yönetin, ödeme aşamasına geçin ve poliçeyi aynı operasyon merkezinden kapatın.</p><div class="hero-badges">@if($open['configured'])<span class="badge ok">● Open Hızlı Teklif bağlantısı hazır</span>@else<span class="badge wait">● Open bağlantısı son aşamada aktive edilecek</span>@endif<span class="badge ok">● Operasyon motoru aktif</span></div></div><div class="flow"><div class="flow-step"><i>1</i><div><b>Ruhsat / Talep</b><span>WhatsApp veya panel</span></div></div><div class="flow-step"><i>2</i><div><b>Araç Bilgileri</b><span>Plaka, motor, şasi</span></div></div><div class="flow-step"><i>3</i><div><b>Open Teklif</b><span>{{ $open['configured'] ? 'Canlı prim sonucu' : 'Kimlik bilgileri bekleniyor' }}</span></div></div><div class="flow-step"><i>4</i><div><b>Ödeme / Poliçe</b><span>Operasyon kapanışı</span></div></div></div></section>
<section class="kpis"><article class="kpi"><small>Aktif İşlem</small><strong>{{ $summary['active'] }}</strong><em>Canlı iş kuyruğu</em></article><article class="kpi"><small>Teklif Kuyruğu</small><strong>{{ $summary['waiting'] }}</strong><em>Open'a hazır</em></article><article class="kpi"><small>Teklif Hazır</small><strong>{{ $summary['quoted'] }}</strong><em>Prim sonucu geldi</em></article><article class="kpi"><small>Ödeme Aşaması</small><strong>{{ $summary['payment'] }}</strong><em>Kapanış bekliyor</em></article><article class="kpi"><small>Kontrol Gereken</small><strong>{{ $summary['attention'] }}</strong><em>Operatör müdahalesi</em></article><article class="kpi"><small>Bugün Poliçelenen</small><strong>{{ $summary['issued_today'] }}</strong><em>Günlük kapanış</em></article></section>
<div class="workspace"><aside class="panel"><div class="panel-head"><h2>Yeni İşlem</h2><p>WhatsApp bağlantısı aktif olduğunda kayıtlar otomatik oluşur. Personel gerektiğinde manuel dosya da açabilir.</p></div><form class="form" wire:submit="createOperation"><div class="field"><label>Müşteri / Firma</label><input class="input" wire:model="customerName" placeholder="Müşteri adı"></div><div class="row2"><div class="field"><label>Telefon</label><input class="input" wire:model="phone" placeholder="05xx..."></div><div class="field"><label>Poliçe Türü</label><select class="select" wire:model="policyType"><option>TRAFIK</option><option>KASKO</option><option>TSS</option><option>DASK</option><option>KONUT</option><option>IMM</option></select></div></div><div class="field"><label>Plaka</label><input class="input" wire:model="plate" placeholder="34ABC123"></div><div class="field"><label>Motor No</label><input class="input" wire:model="motorNumber"></div><div class="field"><label>Şasi No</label><input class="input" wire:model="chassisNumber"></div><div class="field"><label>Ruhsat / Belge No</label><input class="input" wire:model="licenseNumber"></div><button class="btn primary" type="submit">İşlemi Operasyona Al</button><div class="note">Open kimlik bilgisi bağlanana kadar sahte prim oluşturulmaz. Gerçek dosya aynı iş akışında güvenle bekler.</div></form></aside>
<section class="panel"><div class="panel-head"><h2>Canlı Operasyon Kuyruğu</h2><p>Dosyaya tıklayarak işlem detayını, teklifleri, geçmiş aksiyonları ve kapanış adımlarını açın.</p></div><div class="toolbar"><input class="input" wire:model.live.debounce.350ms="search" placeholder="Müşteri, telefon, plaka, motor veya şasi ara..."><div class="filters">@foreach(['active'=>'Aktif','quoted'=>'Teklif Hazır','payment'=>'Ödeme','attention'=>'Kontrol','issued'=>'Poliçelendi','all'=>'Tümü'] as $key=>$label)<button type="button" class="{{ $filter===$key?'active':'' }}" wire:click="$set('filter','{{ $key }}')">{{ $label }}</button>@endforeach</div></div>
@if($cases->isEmpty())<div class="empty">Henüz işlem yok. İlk ruhsat geldiğinde dosya otomatik olarak burada açılacak.</div>@else<div class="cards">@foreach($cases as $case)@php($best=$this->bestPremium($case))@php($cls=in_array($case->status,['needs_attention','failed'])?'attn':($case->status==='quoted'?'quoted':(in_array($case->status,['waiting_vehicle','ready_for_open','open_pending'])?'pending':'')))<article class="case" wire:key="case-{{ $case->id }}"><div><b>#{{ $case->id }} · {{ $case->customer_name ?: 'Müşteri adı bekleniyor' }}</b><span>{{ $case->phone ?: 'Telefon yok' }} · {{ $case->policy_type }}</span><span>{{ $case->created_at->format('d.m.Y H:i') }} · Süre: {{ $this->elapsedLabel($case) }}</span></div><div><b>{{ $case->plate ?: 'Plaka bekleniyor' }}</b><span>Motor: {{ $case->motor_number ?: '—' }}</span><span>Şasi: {{ $case->chassis_number ?: '—' }}</span></div><div><span class="status {{ $cls }}">{{ $case->statusLabel() }}</span><span>{{ $case->integration_status ?: 'entegrasyon bekliyor' }}</span></div><div>@if($best)<div class="price">₺{{ number_format($best,2,',','.') }}</div><span>En iyi prim</span>@else<div class="price">—</div><span>Prim bekleniyor</span>@endif</div><div class="case-actions"><button type="button" class="primary" wire:click="selectCase({{ $case->id }})">Dosyayı Aç</button>@if($case->status==='quoted')<a href="/admin/sigorta-teklif-odeme">Teklif & Ödeme</a>@endif</div></article>@endforeach</div>@endif
</section></div></div></div>

@if($selected)
<div class="detail-overlay" wire:click.self="closeCaseDetail"><aside class="drawer"><div class="drawer-top"><div><div class="eyebrow">İşlem Dosyası #{{ $selected->id }}</div><h2>{{ $selected->customer_name ?: 'Müşteri' }}</h2><p>{{ $selected->phone ?: 'Telefon yok' }} · {{ $selected->policy_type }} · {{ $this->elapsedLabel($selected) }}</p></div><button class="close" wire:click="closeCaseDetail">×</button></div>
@php($step=in_array($selected->status,['quoted','payment_ready','issued'])?3:(in_array($selected->status,['ready_for_open','open_pending'])?2:1))
<div class="progress"><div class="progress-step done"><small>1. Talep</small><b>Dosya Açıldı</b></div><div class="progress-step {{ $step>=2?'done':'' }}"><small>2. Araç</small><b>Bilgiler Hazır</b></div><div class="progress-step {{ $step>=3?'done':'' }}"><small>3. Teklif</small><b>{{ in_array($selected->status,['quoted','payment_ready','issued'])?'Prim Geldi':'Bekleniyor' }}</b></div><div class="progress-step {{ $selected->status==='issued'?'done':'' }}"><small>4. Poliçe</small><b>{{ $selected->status==='issued'?'Tamamlandı':'Kapanış' }}</b></div></div>
<div class="section"><h3>Araç & Dosya Bilgileri</h3><div class="info-grid"><div class="info"><small>Plaka</small><b>{{ $selected->plate ?: '—' }}</b></div><div class="info"><small>Ruhsat / Belge No</small><b>{{ $selected->license_number ?: '—' }}</b></div><div class="info"><small>Motor No</small><b>{{ $selected->motor_number ?: '—' }}</b></div><div class="info"><small>Şasi No</small><b>{{ $selected->chassis_number ?: '—' }}</b></div><div class="info"><small>Araç</small><b>{{ trim(($selected->vehicle_brand ?: '').' '.($selected->vehicle_model ?: '')) ?: '—' }}</b></div><div class="info"><small>Open Teklif ID</small><b>{{ $selected->open_teklif_id ?: 'Henüz bağlı değil' }}</b></div></div></div>
<div class="section"><h3>Teklif Sonuçları</h3>@if($selected->quotes->isEmpty())<div class="empty" style="padding:18px">Henüz prim sonucu gelmedi. Open bağlantısı aktif olduğunda teklif sonuçları burada sıralanacak.</div>@else<div class="quote-grid">@foreach($selected->quotes as $index=>$quote)<div class="quote {{ $index===0?'best':'' }}"><div><b>{{ $quote->company_name ?? $quote->insurer ?? 'Sigorta Şirketi' }}</b><span>{{ $index===0?'En uygun teklif':'Alternatif teklif' }}</span></div><strong>₺{{ number_format((float)$quote->premium,2,',','.') }}</strong></div>@endforeach</div>@endif</div>
<div class="section"><h3>İşlem Geçmişi</h3>@if($selected->events->isEmpty())<div class="empty" style="padding:16px">Henüz işlem hareketi yok.</div>@else<div class="timeline">@foreach($selected->events->take(8) as $event)<div class="event"><i></i><div><b>{{ $event->title ?: $event->type }}</b><span>{{ $event->created_at?->format('d.m.Y H:i') }}</span></div></div>@endforeach</div>@endif</div>
<div class="drawer-actions">@if(!$selected->open_teklif_id)<div class="ins-inline"><input class="input" style="width:130px" wire:model="openTeklifIds.{{ $selected->id }}" placeholder="Open Teklif ID"><button wire:click="saveOpenTeklifId({{ $selected->id }})">Open'a Bağla</button></div>@else<button wire:click="syncOpen({{ $selected->id }})">Open Verisini Yenile</button>@endif @if(in_array($selected->status,['quoted','payment_ready'],true))<a class="primary" href="/admin/sigorta-teklif-odeme">Teklif & Ödeme Merkezine Git</a>@endif</div>
</aside></div>
@endif
</x-filament-panels::page>
