<x-filament-panels::page>
<style>
.fi-sidebar,.fi-topbar,#wai-sidebar-toggle{display:none!important}.fi-main{margin-inline-start:0!important;padding:0!important;background:#07111f!important}.fi-main-ctn{padding-top:0!important}.fi-page-header{display:none!important}.fi-page{padding:0!important}.fi-body{background:#07111f!important}
.tpc-shell{min-height:100vh;background:radial-gradient(circle at 8% 0,rgba(37,99,235,.18),transparent 28%),radial-gradient(circle at 92% 0,rgba(14,165,233,.13),transparent 24%),linear-gradient(180deg,#06101d,#081522 44%,#091522);color:#eef7ff;padding:20px}.wrap{max-width:1560px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.brand{display:flex;align-items:center;gap:12px}.logo{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;font-weight:950;background:linear-gradient(135deg,#2563eb,#06b6d4);box-shadow:0 14px 34px rgba(37,99,235,.28)}.brand b{display:block;font-size:15px}.brand span{display:block;color:#8ba5bd;font-size:11px;margin-top:2px}.nav{display:flex;gap:8px;flex-wrap:wrap}.nav a{padding:10px 13px;border:1px solid #26394f;border-radius:12px;background:#0c1a2a;color:#a7bdd2;text-decoration:none;font-size:11px;font-weight:900}.nav a.active{color:#fff;border-color:transparent;background:linear-gradient(135deg,#2563eb,#0891b2)}
.hero{padding:28px;border-radius:28px;border:1px solid rgba(148,163,184,.12);background:linear-gradient(145deg,rgba(15,29,49,.98),rgba(7,17,31,.98));box-shadow:0 24px 70px rgba(0,0,0,.22)}.eyebrow{font-size:10px;letter-spacing:.17em;text-transform:uppercase;color:#78ddf7;font-weight:950}.hero h1{margin:8px 0 10px;font-size:clamp(34px,4vw,56px);line-height:1;letter-spacing:-.045em}.hero p{margin:0;max-width:920px;color:#b8c9d9;font-size:14px;line-height:1.7}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-top:14px}.kpi{padding:18px;border:1px solid #233448;background:linear-gradient(145deg,#0d1a2a,#0a1624);border-radius:18px;box-shadow:0 13px 30px rgba(0,0,0,.13)}.kpi small{display:block;color:#8ba0b5;font-size:10px;font-weight:850}.kpi strong{display:block;margin-top:8px;font-size:30px;line-height:1;font-weight:950}.kpi em{display:block;margin-top:8px;color:#6c8399;font-size:9px;font-style:normal}
.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px;margin-top:14px}.panel{border:1px solid #223348;background:rgba(11,23,39,.97);border-radius:21px;overflow:hidden;box-shadow:0 16px 42px rgba(0,0,0,.16)}.head{padding:17px 18px;border-bottom:1px solid rgba(148,163,184,.1)}.head h2{margin:0;font-size:16px;font-weight:950}.head p{margin:5px 0 0;color:#8399ae;font-size:10px;line-height:1.55}.rows{display:grid}.row{display:grid;grid-template-columns:1.2fr .6fr .6fr .6fr;gap:10px;align-items:center;padding:13px 16px;border-bottom:1px solid #1c2b3c}.row:last-child{border-bottom:0}.row b{font-size:11px}.row span{display:block;color:#7e95aa;font-size:9px;margin-top:3px}.metric{font-size:16px;font-weight:950}.case-row{display:grid;grid-template-columns:1.2fr .8fr .7fr;gap:10px;padding:13px 16px;border-bottom:1px solid #1c2b3c}.case-row:last-child{border-bottom:0}.case-row b{font-size:11px}.case-row span{display:block;color:#7e95aa;font-size:9px;margin-top:3px}.status{display:inline-flex;padding:6px 8px;border-radius:999px;font-size:8px;font-weight:950;background:#203247;color:#c7d6e4}.status.ok{background:rgba(16,185,129,.13);color:#99e6c5}.status.warn{background:rgba(245,158,11,.13);color:#f9d78c}.empty{padding:40px 20px;text-align:center;color:#7e95aa;font-size:11px}
@media(max-width:1050px){.kpis{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}@media(max-width:700px){.tpc-shell{padding:11px}.top{flex-direction:column;align-items:flex-start}.nav{width:100%;display:grid;grid-template-columns:1fr 1fr}.nav a{text-align:center}.hero{padding:20px}.hero h1{font-size:34px}.kpis{grid-template-columns:1fr 1fr}.row,.case-row{grid-template-columns:1fr 1fr}}
</style>
@php($s=$this->summary)
@php($team=$this->team)
@php($recent=$this->recentCases)
<div class="tpc-shell"><div class="wrap">
<div class="top"><div class="brand"><div class="logo">TPC</div><div><b>TPC Insurance OS</b><span>Doğuş Topçu Sigorta • Yönetici Kontrol Merkezi</span></div></div><nav class="nav"><a href="/admin/sigorta-operasyon">Operasyon</a><a href="/admin/sigorta-yenileme">Geri Kazanım</a><a href="/admin/sigorta-ekip">Ekip</a><a class="active" href="/admin/sigorta-yonetici">Yönetici</a></nav></div>
<section class="hero"><div class="eyebrow">Yönetici Görünümü</div><h1>Operasyonun tamamını tek bakışta yönetin.</h1><p>Günlük iş yükü, poliçeleşme, ekip performansı, dönüşüm oranı ve geciken dosyaları tek ekranda takip edin. Bu ekran, yüksek hacimli sigorta operasyonunda karar vermeyi hızlandırmak için tasarlandı.</p></section>
<section class="kpis">
<article class="kpi"><small>Bugün Gelen</small><strong>{{ $s['today_inbound'] }}</strong><em>Yeni sigorta işlemi</em></article>
<article class="kpi"><small>Bugün Poliçelenen</small><strong>{{ $s['today_issued'] }}</strong><em>Kapanan işlem</em></article>
<article class="kpi"><small>Aktif İş Yükü</small><strong>{{ $s['active'] }}</strong><em>Operasyon kuyruğu</em></article>
<article class="kpi"><small>Kontrol Gereken</small><strong>{{ $s['attention'] }}</strong><em>Müdahale bekliyor</em></article>
<article class="kpi"><small>Aylık Dönüşüm</small><strong>%{{ number_format($s['conversion'],1,',','.') }}</strong><em>{{ $s['month_issued'] }} / {{ $s['month_created'] }} işlem</em></article>
<article class="kpi"><small>Ort. Kapanış Süresi</small><strong>{{ $s['avg_minutes'] !== null ? number_format($s['avg_minutes'],1,',','.') : '—' }}</strong><em>dakika</em></article>
<article class="kpi"><small>Bu Ay Poliçe</small><strong>{{ $s['month_issued'] }}</strong><em>Tamamlanan dosya</em></article>
<article class="kpi"><small>En Düşük Görülen Prim</small><strong>{{ $s['quoted_value'] > 0 ? number_format($s['quoted_value'],2,',','.') : '—' }}</strong><em>TL</em></article>
</section>
<div class="grid">
<section class="panel"><div class="head"><h2>Ekip Performansı</h2><p>Aktif iş yükü ve poliçeleşme sonuçları.</p></div>@if($team->isEmpty())<div class="empty">Henüz ekip verisi oluşmadı.</div>@else<div class="rows">@foreach($team as $m)<div class="row"><div><b>{{ $m['name'] }}</b><span>{{ $m['email'] }}</span></div><div><span>Aktif</span><div class="metric">{{ $m['active'] }}</div></div><div><span>Bugün</span><div class="metric">{{ $m['issued_today'] }}</div></div><div><span>Bu Ay</span><div class="metric">{{ $m['issued_month'] }}</div></div></div>@endforeach</div>@endif</section>
<section class="panel"><div class="head"><h2>Son Operasyonlar</h2><p>Sistemdeki en güncel işlem hareketleri.</p></div>@if($recent->isEmpty())<div class="empty">Henüz işlem yok.</div>@else<div class="rows">@foreach($recent as $case)<div class="case-row"><div><b>#{{ $case->id }} · {{ $case->customer_name ?: 'Müşteri' }}</b><span>{{ $case->plate ?: 'Plaka bekleniyor' }} · {{ $case->policy_type }}</span></div><div><span>Personel</span><b>{{ $case->assignedUser?->name ?: 'Atanmadı' }}</b></div><div><span class="status {{ $case->status==='issued'?'ok':(in_array($case->status,['failed','needs_attention'])?'warn':'') }}">{{ $case->statusLabel() }}</span></div></div>@endforeach</div>@endif</section>
</div>
</div></div>
</x-filament-panels::page>
