<x-filament-panels::page>
<style>
.fi-sidebar,.fi-topbar,#wai-sidebar-toggle{display:none!important}.fi-main{margin-inline-start:0!important;padding:0!important;background:#07111f!important}.fi-main-ctn{padding-top:0!important}.fi-page-header{display:none!important}.fi-page{padding:0!important}.fi-body{background:#07111f!important}
.shell{min-height:100vh;background:radial-gradient(circle at 9% 0,rgba(37,99,235,.18),transparent 27%),radial-gradient(circle at 94% 0,rgba(16,185,129,.12),transparent 24%),linear-gradient(180deg,#06101d,#081522 42%,#091522);color:#eef7ff;padding:20px}.wrap{max-width:1560px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.brand{display:flex;align-items:center;gap:12px}.logo{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;font-weight:950;background:linear-gradient(135deg,#2563eb,#06b6d4)}.brand b{display:block;font-size:15px}.brand span{display:block;color:#8ba5bd;font-size:11px;margin-top:2px}.nav{display:flex;gap:8px;flex-wrap:wrap}.nav a{padding:10px 13px;border:1px solid #26394f;border-radius:12px;background:#0c1a2a;color:#a7bdd2;text-decoration:none;font-size:11px;font-weight:900}.nav a.active{color:#fff;border-color:transparent;background:linear-gradient(135deg,#059669,#0f766e)}
.hero{padding:28px;border-radius:28px;border:1px solid rgba(148,163,184,.12);background:linear-gradient(145deg,rgba(15,29,49,.98),rgba(7,17,31,.98));box-shadow:0 24px 70px rgba(0,0,0,.22)}.eyebrow{font-size:10px;letter-spacing:.17em;text-transform:uppercase;color:#86efac;font-weight:950}.hero h1{margin:8px 0 10px;font-size:clamp(34px,4vw,56px);line-height:1;letter-spacing:-.045em}.hero p{margin:0;max-width:900px;color:#b8c9d9;font-size:14px;line-height:1.7}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-top:14px}.kpi{padding:18px;border:1px solid #233448;background:linear-gradient(145deg,#0d1a2a,#0a1624);border-radius:18px}.kpi small{display:block;color:#8ba0b5;font-size:10px;font-weight:850}.kpi strong{display:block;margin-top:8px;font-size:30px;font-weight:950}.kpi em{display:block;margin-top:7px;color:#6c8399;font-size:9px;font-style:normal}
.panel{margin-top:14px;border:1px solid #223348;background:rgba(11,23,39,.97);border-radius:21px;overflow:hidden}.head{padding:17px 18px;border-bottom:1px solid rgba(148,163,184,.1)}.head h2{margin:0;font-size:16px;font-weight:950}.head p{margin:5px 0 0;color:#8399ae;font-size:10px}.toolbar{display:flex;gap:7px;flex-wrap:wrap;padding:13px 14px;border-bottom:1px solid rgba(148,163,184,.1)}.input{width:300px;max-width:100%;padding:11px 12px;border-radius:11px;border:1px solid #304359;background:#081522;color:#f4f8fc;font-size:12px}.filters{display:flex;gap:6px;flex-wrap:wrap}.filters button{padding:8px 9px;border-radius:999px;border:1px solid #304359;background:#081522;color:#9fb2c5;font-size:9px;font-weight:850;cursor:pointer}.filters button.active{color:#fff;background:#114a3d;border-color:#1d7a64}.cards{display:grid;gap:10px;padding:12px}.card{display:grid;grid-template-columns:1.1fr .8fr .8fr auto;gap:12px;align-items:center;padding:14px;border:1px solid #23364b;border-radius:15px;background:linear-gradient(145deg,#0b1827,#0a1522)}.card b{display:block;font-size:11px}.card span{display:block;color:#7e95aa;font-size:9px;margin-top:3px}.quote{font-size:19px;font-weight:950}.quote small{display:block;color:#7e95aa;font-size:8px;font-weight:800;margin-bottom:4px}.status{display:inline-flex;padding:6px 8px;border-radius:999px;font-size:8px;font-weight:950;background:#203247;color:#c7d6e4}.status.payment{background:rgba(16,185,129,.13);color:#99e6c5}.status.quoted{background:rgba(37,99,235,.15);color:#a7c7ff}.actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.actions button{padding:9px 10px;border-radius:9px;border:1px solid #30465f;background:#0b1928;color:#c9d9e8;font-size:8px;font-weight:900;cursor:pointer}.actions .primary{color:#fff;border:0;background:linear-gradient(135deg,#2563eb,#0891b2)}.actions .success{color:#fff;border:0;background:linear-gradient(135deg,#059669,#0f766e)}.empty{padding:44px 20px;text-align:center;color:#7e95aa;font-size:11px}
@media(max-width:900px){.kpis{grid-template-columns:repeat(2,1fr)}.card{grid-template-columns:1fr 1fr}.actions{justify-content:flex-start}}@media(max-width:650px){.shell{padding:11px}.top{flex-direction:column;align-items:flex-start}.nav{width:100%;display:grid;grid-template-columns:1fr 1fr}.nav a{text-align:center}.hero{padding:20px}.hero h1{font-size:34px}.card{grid-template-columns:1fr}.input{width:100%}}
</style>
@php($s=$this->summary)
@php($cases=$this->cases)
<div class="shell"><div class="wrap">
<div class="top"><div class="brand"><div class="logo">TPC</div><div><b>TPC Insurance OS</b><span>Doğuş Topçu Sigorta • Teklif & Ödeme Merkezi</span></div></div><nav class="nav"><a href="/admin/sigorta-operasyon">Operasyon</a><a href="/admin/sigorta-yenileme">Geri Kazanım</a><a href="/admin/sigorta-ekip">Ekip</a><a href="/admin/sigorta-yonetici">Yönetici</a><a class="active" href="/admin/sigorta-teklif-odeme">Teklif & Ödeme</a></nav></div>
<section class="hero"><div class="eyebrow">Tekliften Kapanışa</div><h1>En iyi primi görün, ödemeye geçin, poliçeyi kapatın.</h1><p>Open’dan gelen teklif sonuçlarını tek listede yönetin. En uygun primi öne çıkarın, dosyayı ödeme aşamasına taşıyın ve poliçeleşen işlemi aynı merkezden kapatın.</p></section>
<section class="kpis"><article class="kpi"><small>Teklif Hazır</small><strong>{{ $s['quoted'] }}</strong><em>Prim sonucu gelen</em></article><article class="kpi"><small>Ödeme Bekliyor</small><strong>{{ $s['payment'] }}</strong><em>Kapanış aşaması</em></article><article class="kpi"><small>Bugün Poliçelenen</small><strong>{{ $s['issued_today'] }}</strong><em>Tamamlanan işlem</em></article><article class="kpi"><small>Kontrol Gereken</small><strong>{{ $s['attention'] }}</strong><em>Müdahale bekliyor</em></article></section>
<section class="panel"><div class="head"><h2>Teklif & Ödeme Kuyruğu</h2><p>Teklif sonucu gelen ve ödeme aşamasına geçen dosyalar.</p></div><div class="toolbar"><input class="input" wire:model.live.debounce.350ms="search" placeholder="Müşteri, telefon veya plaka ara..."><div class="filters">@foreach(['quoted'=>'Teklif Hazır','payment'=>'Ödeme','issued'=>'Poliçelendi','attention'=>'Kontrol','all'=>'Tümü'] as $key=>$label)<button type="button" class="{{ $filter===$key?'active':'' }}" wire:click="$set('filter','{{ $key }}')">{{ $label }}</button>@endforeach</div></div>
@if($cases->isEmpty())<div class="empty">Bu aşamada bekleyen dosya yok.</div>@else<div class="cards">@foreach($cases as $case)@php($best=$this->bestQuote($case))<article class="card"><div><b>#{{ $case->id }} · {{ $case->customer_name ?: 'Müşteri' }}</b><span>{{ $case->phone ?: 'Telefon yok' }} · {{ $case->policy_type }}</span><span>{{ $case->plate ?: 'Plaka bekleniyor' }}</span></div><div><span>Personel</span><b>{{ $case->assignedUser?->name ?: 'Atanmadı' }}</b><span>Open ID: {{ $case->open_teklif_id ?: '—' }}</span></div><div>@if($best)<small>En iyi prim</small><div class="quote">{{ number_format((float)$best->premium,2,',','.') }} {{ $best->currency ?: 'TL' }}</div><span>{{ $best->company_name ?: $best->provider ?: 'Sigorta şirketi' }}</span>@else<span class="status {{ $case->status==='payment_ready'?'payment':($case->status==='quoted'?'quoted':'') }}">{{ $case->statusLabel() }}</span>@endif</div><div class="actions">@if($case->status==='quoted')<button class="primary" wire:click="moveToPayment({{ $case->id }})">Ödemeye Geç</button>@endif @if($case->status==='payment_ready')<button class="success" wire:click="markIssued({{ $case->id }})">Poliçeyi Tamamla</button>@endif</div></article>@endforeach</div>@endif
</section>
</div></div>
</x-filament-panels::page>
