<x-filament-panels::page>
<style>
.fi-sidebar,.fi-topbar,#wai-sidebar-toggle{display:none!important}.fi-main{margin-inline-start:0!important;padding:0!important;background:#07111f!important}.fi-main-ctn,.fi-page,.fi-body{padding:0!important;background:#07111f!important}.fi-page-header{display:none!important}
.shell{min-height:100vh;background:radial-gradient(circle at 8% 0,rgba(37,99,235,.18),transparent 28%),radial-gradient(circle at 94% 0,rgba(16,185,129,.12),transparent 24%),linear-gradient(180deg,#06101d,#081522 42%,#091522);color:#eef7ff;padding:20px}.wrap{max-width:1560px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.brand{display:flex;align-items:center;gap:12px}.logo{width:48px;height:48px;border-radius:16px;display:grid;place-items:center;font-weight:950;background:linear-gradient(135deg,#2563eb,#06b6d4);box-shadow:0 14px 34px rgba(37,99,235,.25)}.brand b{display:block;font-size:15px}.brand span{display:block;color:#8ba5bd;font-size:11px;margin-top:2px}.nav{display:flex;gap:7px;flex-wrap:wrap}.nav a{padding:10px 12px;border:1px solid #26394f;border-radius:12px;background:#0c1a2a;color:#a7bdd2;text-decoration:none;font-size:10px;font-weight:900}.nav a.active{color:#fff;border-color:transparent;background:linear-gradient(135deg,#059669,#0f766e)}
.hero{display:grid;grid-template-columns:1.2fr .8fr;gap:18px;padding:28px;border-radius:28px;border:1px solid rgba(148,163,184,.12);background:linear-gradient(145deg,rgba(15,29,49,.98),rgba(7,17,31,.98));box-shadow:0 24px 70px rgba(0,0,0,.22)}.eyebrow{font-size:10px;letter-spacing:.17em;text-transform:uppercase;color:#86efac;font-weight:950}.hero h1{margin:8px 0 10px;font-size:clamp(34px,4vw,56px);line-height:1;letter-spacing:-.045em}.hero p{margin:0;max-width:900px;color:#b8c9d9;font-size:14px;line-height:1.7}.closure-flow{display:grid;gap:8px;align-content:center}.flow-step{display:flex;gap:10px;align-items:center;padding:12px 13px;border:1px solid #283b50;border-radius:14px;background:#0a1726}.flow-step i{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;font-style:normal;font-size:10px;font-weight:950;background:#123c34;color:#9ff0cf}.flow-step b{font-size:11px}.flow-step span{display:block;color:#7d94aa;font-size:9px;margin-top:2px}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-top:14px}.kpi{padding:18px;border:1px solid #233448;background:linear-gradient(145deg,#0d1a2a,#0a1624);border-radius:18px}.kpi small{display:block;color:#8ba0b5;font-size:10px;font-weight:850}.kpi strong{display:block;margin-top:8px;font-size:30px;font-weight:950}.kpi em{display:block;margin-top:7px;color:#6c8399;font-size:9px;font-style:normal}
.panel{margin-top:14px;border:1px solid #223348;background:rgba(11,23,39,.97);border-radius:21px;overflow:hidden}.head{padding:17px 18px;border-bottom:1px solid rgba(148,163,184,.1)}.head h2{margin:0;font-size:16px;font-weight:950}.head p{margin:5px 0 0;color:#8399ae;font-size:10px}.toolbar{display:flex;gap:7px;flex-wrap:wrap;padding:13px 14px;border-bottom:1px solid rgba(148,163,184,.1)}.input,.select{padding:10px 11px;border-radius:10px;border:1px solid #304359;background:#081522;color:#f4f8fc;font-size:10px;outline:none}.toolbar .input{width:310px;max-width:100%}.filters{display:flex;gap:6px;flex-wrap:wrap}.filters button{padding:8px 9px;border-radius:999px;border:1px solid #304359;background:#081522;color:#9fb2c5;font-size:9px;font-weight:850;cursor:pointer}.filters button.active{color:#fff;background:#114a3d;border-color:#1d7a64}
.cards{display:grid;gap:12px;padding:12px}.card{border:1px solid #23364b;border-radius:17px;background:linear-gradient(145deg,#0b1827,#0a1522);overflow:hidden}.card-top{display:grid;grid-template-columns:1.1fr .8fr .8fr auto;gap:12px;align-items:center;padding:14px}.card b{display:block;font-size:11px}.card span{display:block;color:#7e95aa;font-size:9px;margin-top:3px}.status{display:inline-flex;padding:6px 8px;border-radius:999px;font-size:8px;font-weight:950;background:#203247;color:#c7d6e4}.status.payment{background:rgba(16,185,129,.13);color:#99e6c5}.status.quoted{background:rgba(37,99,235,.15);color:#a7c7ff}.status.issued{background:rgba(16,185,129,.16);color:#a7f3d0}.quote-summary{font-size:18px;font-weight:950}.quote-summary small{display:block;color:#7e95aa;font-size:8px;font-weight:800;margin-bottom:4px}.actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.actions button{padding:9px 10px;border-radius:9px;border:1px solid #30465f;background:#0b1928;color:#c9d9e8;font-size:8px;font-weight:900;cursor:pointer}.actions .primary{color:#fff;border:0;background:linear-gradient(135deg,#2563eb,#0891b2)}.actions .success{color:#fff;border:0;background:linear-gradient(135deg,#059669,#0f766e)}button:disabled{opacity:.45;cursor:not-allowed}
.quote-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px;padding:0 14px 14px}.quote-option{padding:11px;border:1px solid #273b52;border-radius:12px;background:#081522}.quote-option.selected{border-color:rgba(16,185,129,.55);background:rgba(16,185,129,.06)}.quote-option small{display:block;color:#7e95aa;font-size:8px}.quote-option strong{display:block;margin-top:4px;font-size:17px}.quote-option button{margin-top:8px;width:100%;padding:8px;border-radius:8px;border:1px solid #315069;background:#0c1b2b;color:#d6e5f1;font-size:8px;font-weight:900;cursor:pointer}.quote-option.selected button{border-color:rgba(16,185,129,.4);color:#9ff0cf}
.closure{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:0 14px 14px}.closure-box{padding:11px;border:1px solid #26394f;border-radius:12px;background:#081522}.closure-box label{display:block;color:#8fa6bc;font-size:8px;font-weight:900;margin-bottom:5px}.closure-box .input,.closure-box .select{width:100%}.closure-box button{width:100%;margin-top:7px;padding:9px;border:0;border-radius:9px;background:linear-gradient(135deg,#059669,#0f766e);color:#fff;font-size:8px;font-weight:900;cursor:pointer}.policy-line{padding:0 14px 14px;color:#9fb3c6;font-size:9px}.empty{padding:44px 20px;text-align:center;color:#7e95aa;font-size:11px}
@media(max-width:980px){.hero{grid-template-columns:1fr}.kpis{grid-template-columns:repeat(2,1fr)}.card-top{grid-template-columns:1fr 1fr}.actions{justify-content:flex-start}.closure{grid-template-columns:1fr}}
@media(max-width:650px){.shell{padding:11px}.top{flex-direction:column;align-items:flex-start}.nav{width:100%;display:grid;grid-template-columns:1fr 1fr}.nav a{text-align:center}.hero{padding:20px}.hero h1{font-size:34px}.card-top{grid-template-columns:1fr}.toolbar .input{width:100%}}
</style>
@php($s=$this->summary)
@php($cases=$this->cases)
<div class="shell"><div class="wrap">
@include('filament.partials.insurance-navigation', ['active' => 'payment'])
<section class="hero"><div><div class="eyebrow">Tekliften Kapanışa</div><h1>Prim geldiğinde karar saniyeler içinde verilsin.</h1><p>Open’dan gelen teklifleri karşılaştırın, seçilen teklifi sabitleyin, ödeme kaydını tamamlayın ve poliçe numarasıyla dosyayı kapatın. Her adım işlem geçmişine işlenir.</p></div><div class="closure-flow"><div class="flow-step"><i>1</i><div><b>Teklifleri Karşılaştır</b><span>Prim sonuçları tek kartta</span></div></div><div class="flow-step"><i>2</i><div><b>Teklifi Seç</b><span>Dosyanın seçili primi sabitlenir</span></div></div><div class="flow-step"><i>3</i><div><b>Ödemeyi Kaydet</b><span>Yöntem ve referans takibi</span></div></div><div class="flow-step"><i>4</i><div><b>Poliçeyi Kapat</b><span>Poliçe numarası ve kapanış kaydı</span></div></div></div></section>
<section class="kpis"><article class="kpi"><small>Teklif Hazır</small><strong>{{ $s['quoted'] }}</strong><em>Prim sonucu gelen</em></article><article class="kpi"><small>Ödeme Bekliyor</small><strong>{{ $s['payment'] }}</strong><em>Kapanış aşaması</em></article><article class="kpi"><small>Bugün Poliçelenen</small><strong>{{ $s['issued_today'] }}</strong><em>Tamamlanan işlem</em></article><article class="kpi"><small>Kontrol Gereken</small><strong>{{ $s['attention'] }}</strong><em>Müdahale bekliyor</em></article></section>
<section class="panel"><div class="head"><h2>Teklif & Ödeme Kuyruğu</h2><p>Tekliften poliçe kapanışına kadar tüm ticari adımlar.</p></div><div class="toolbar"><input class="input" wire:model.live.debounce.350ms="search" placeholder="Müşteri, telefon, plaka, poliçe veya ödeme ref. ara..."><div class="filters">@foreach(['quoted'=>'Teklif Hazır','payment'=>'Ödeme','issued'=>'Poliçelendi','attention'=>'Kontrol','all'=>'Tümü'] as $key=>$label)<button type="button" class="{{ $filter===$key?'active':'' }}" wire:click="$set('filter','{{ $key }}')">{{ $label }}</button>@endforeach</div></div>
@if($cases->isEmpty())<div class="empty">Bu aşamada bekleyen dosya yok.</div>@else<div class="cards">@foreach($cases as $case)@php($best=$this->bestQuote($case))<article class="card">
<div class="card-top"><div><b>#{{ $case->id }} · {{ $case->customer_name ?: 'Müşteri' }}</b><span>{{ $case->phone ?: 'Telefon yok' }} · {{ $case->policy_type }}</span><span>{{ $case->plate ?: 'Plaka bekleniyor' }}</span></div><div><span>Personel</span><b>{{ $case->assignedUser?->name ?: 'Atanmadı' }}</b><span>Open ID: {{ $case->open_teklif_id ?: '—' }}</span></div><div>@if($case->selectedQuote)<small>Seçili prim</small><div class="quote-summary">{{ number_format((float)$case->selectedQuote->premium,2,',','.') }} {{ $case->selectedQuote->currency ?: 'TRY' }}</div><span>{{ $case->selectedQuote->company_name ?: $case->selectedQuote->provider }}</span>@elseif($best)<small>En iyi prim</small><div class="quote-summary">{{ number_format((float)$best->premium,2,',','.') }} {{ $best->currency ?: 'TRY' }}</div><span>{{ $best->company_name ?: $best->provider }}</span>@else<span class="status {{ $case->status==='payment_ready'?'payment':($case->status==='quoted'?'quoted':($case->status==='issued'?'issued':'')) }}">{{ $case->statusLabel() }}</span>@endif</div><div class="actions">@if($case->status==='quoted')<button class="primary" wire:click="moveToPayment({{ $case->id }})" @disabled(!$case->selected_quote_id)>Ödeme Aşamasına Geç</button>@endif</div></div>
@if($case->quotes->isNotEmpty())<div class="quote-list">@foreach($case->quotes as $quote)<div class="quote-option {{ (int)$case->selected_quote_id===(int)$quote->id?'selected':'' }}"><small>{{ $quote->company_name ?: $quote->provider ?: 'Sigorta Şirketi' }}</small><strong>{{ $quote->premium!==null ? number_format((float)$quote->premium,2,',','.') : '—' }} {{ $quote->currency ?: 'TRY' }}</strong><button wire:click="selectQuote({{ $case->id }},{{ $quote->id }})" @disabled($quote->premium===null || (float)$quote->premium<=0)>{{ (int)$case->selected_quote_id===(int)$quote->id?'✓ Seçili Teklif':'Bu Teklifi Seç' }}</button></div>@endforeach</div>@endif
@if($case->status==='payment_ready')<div class="closure">@if($case->payment_status!=='paid')<div class="closure-box"><label>Ödeme Yöntemi</label><select class="select" wire:model="paymentMethods.{{ $case->id }}"><option value="">Seçiniz</option><option value="credit_card">Kredi Kartı</option><option value="bank_transfer">Havale / EFT</option><option value="other">Diğer</option></select></div><div class="closure-box"><label>Ödeme Referansı</label><input class="input" wire:model="paymentReferences.{{ $case->id }}" placeholder="Kart / havale işlem no"><button wire:click="markPaymentPaid({{ $case->id }})">Ödemeyi Kaydet</button></div>@else<div class="closure-box"><label>Ödeme Durumu</label><b>✓ Ödeme kaydedildi</b><span>{{ $case->payment_method }}@if($case->payment_reference) · {{ $case->payment_reference }}@endif</span></div>@endif<div class="closure-box"><label>Poliçe Numarası</label><input class="input" wire:model="policyNumbers.{{ $case->id }}" placeholder="Poliçe no" @disabled($case->payment_status!=='paid')><button wire:click="markIssued({{ $case->id }})" @disabled($case->payment_status!=='paid')>Poliçeyi Kapat</button>@if($case->payment_status!=='paid')<span>Poliçe kapanışı için önce ödeme kaydedilmelidir.</span>@endif</div></div>@endif
@if($case->status==='issued')<div class="policy-line">✓ Poliçe tamamlandı @if($case->policy_number) · Poliçe No: <b>{{ $case->policy_number }}</b>@endif @if($case->issued_at) · {{ $case->issued_at->format('d.m.Y H:i') }}@endif</div>@endif
</article>@endforeach</div>@endif
</section>
</div></div>
</x-filament-panels::page>
