<x-filament-panels::page>
<style>
.fi-sidebar,.fi-topbar,.fi-page-header,#wai-sidebar-toggle{display:none!important}.fi-main{margin-inline-start:0!important;padding:0!important;background:#07101d!important}.fi-main-ctn{padding-top:0!important}.fi-page{padding:0!important}.fi-body{background:#07101d!important}.fi-page>div{max-width:none!important}
.ren-shell{min-height:100vh;background:radial-gradient(circle at 0 0,rgba(244,63,94,.14),transparent 25%),radial-gradient(circle at 100% 0,rgba(59,130,246,.14),transparent 25%),linear-gradient(180deg,#07101d,#0a1420 44%,#08131f);color:#f6f8fb;padding:20px;font-family:Inter,ui-sans-serif,system-ui}.ren-wrap{max-width:1580px;margin:auto}.ren-top{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:18px}.ren-brand{display:flex;align-items:center;gap:13px}.ren-logo{width:50px;height:50px;border-radius:16px;display:grid;place-items:center;font-weight:950;background:linear-gradient(135deg,#2563eb,#8b5cf6 48%,#e11d48);box-shadow:0 16px 40px rgba(225,29,72,.18)}.ren-brand b{display:block;font-size:16px}.ren-brand span{display:block;margin-top:3px;color:#9a9fb1;font-size:12px}.ren-nav{display:flex;gap:8px;flex-wrap:wrap}.ren-nav a{padding:10px 13px;border:1px solid #31364a;border-radius:12px;background:#111827;color:#aeb4c5;text-decoration:none;font-size:12px;font-weight:850}.ren-nav a.active{color:#fff;border-color:transparent;background:linear-gradient(135deg,#4f46e5,#db2777);box-shadow:0 12px 30px rgba(219,39,119,.18)}
.ren-hero{position:relative;overflow:hidden;padding:30px;border-radius:30px;border:1px solid rgba(148,163,184,.13);background:linear-gradient(145deg,rgba(20,24,39,.98),rgba(10,17,30,.98));box-shadow:0 28px 80px rgba(0,0,0,.28)}.ren-hero:after{content:"";position:absolute;width:460px;height:460px;border-radius:50%;right:-210px;top:-250px;background:radial-gradient(circle,rgba(244,63,94,.10),transparent 65%)}.ren-eyebrow{font-size:11px;letter-spacing:.17em;text-transform:uppercase;color:#fda4af;font-weight:950}.ren-hero h1{max-width:1100px;margin:10px 0 12px;font-size:clamp(38px,4.5vw,64px);line-height:.98;letter-spacing:-.05em}.ren-hero p{max-width:950px;margin:0;color:#c4c8d3;font-size:15px;line-height:1.75}.ren-badge{display:inline-flex;margin-top:16px;padding:8px 11px;border-radius:999px;border:1px solid rgba(244,63,94,.28);background:rgba(244,63,94,.08);color:#fecdd3;font-size:10px;font-weight:950}
.ren-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:16px}.ren-kpi{padding:18px 19px;border-radius:19px;border:1px solid #2a3244;background:linear-gradient(145deg,#111b2a,#0c1623);box-shadow:0 14px 34px rgba(0,0,0,.14)}.ren-kpi small{display:block;color:#999fb0;font-size:11px;font-weight:850}.ren-kpi strong{display:block;margin-top:7px;font-size:32px;line-height:1;font-weight:950}.ren-kpi span{display:block;margin-top:8px;color:#747b8f;font-size:10px}
.ren-work{display:grid;grid-template-columns:330px 1fr;gap:16px;margin-top:16px;align-items:start}.ren-card{border:1px solid #293448;border-radius:22px;background:rgba(15,24,39,.97);box-shadow:0 18px 48px rgba(0,0,0,.18);overflow:hidden}.ren-head{padding:18px 19px;border-bottom:1px solid rgba(148,163,184,.10)}.ren-head h2{margin:0;font-size:17px;font-weight:950}.ren-head p{margin:5px 0 0;color:#8c94a6;font-size:11px;line-height:1.55}.ren-form{padding:17px;display:grid;gap:11px}.ren-field label{display:block;margin-bottom:6px;color:#a9afbf;font-size:11px;font-weight:850}.ren-input{width:100%;padding:11px 12px;border-radius:11px;border:1px solid #394258;background:#0a1421;color:#f7f8fb;font-size:13px;outline:none}.ren-input:focus{border-color:#ec4899;box-shadow:0 0 0 3px rgba(236,72,153,.08)}.ren-btn{border:0;border-radius:11px;padding:11px 13px;color:white;background:linear-gradient(135deg,#4f46e5,#db2777);font-size:11px;font-weight:900;cursor:pointer;box-shadow:0 10px 24px rgba(219,39,119,.16)}
.ren-toolbar{display:flex;gap:8px;flex-wrap:wrap;padding:13px 15px;border-bottom:1px solid rgba(148,163,184,.10)}.ren-toolbar .ren-input{max-width:330px}.ren-filter{display:flex;gap:6px;flex-wrap:wrap}.ren-filter button{padding:8px 10px;border-radius:999px;border:1px solid #394258;background:#0b1522;color:#a5adbd;font-size:10px;font-weight:850;cursor:pointer}.ren-filter button.active{color:#fff;border-color:#9f1239;background:#431422}.ren-list{padding:14px;display:grid;gap:11px}.ren-case{display:grid;grid-template-columns:1.4fr 1.1fr .7fr .8fr auto;gap:14px;align-items:center;padding:16px;border:1px solid #2c374b;border-radius:18px;background:linear-gradient(145deg,#111b2a,#0b1623)}.ren-main b{display:block;font-size:13px;color:#f7f8fb}.ren-main span{display:block;margin-top:4px;color:#868ea1;font-size:10px}.ren-status{display:inline-flex;padding:7px 9px;border-radius:999px;font-size:9px;font-weight:950;background:#2a3343;color:#cfd5df}.ren-status.detected{background:rgba(244,63,94,.14);color:#fecdd3}.ren-status.assigned{background:rgba(79,70,229,.16);color:#c7d2fe}.ren-status.recovered{background:rgba(16,185,129,.14);color:#a7f3d0}.ren-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.ren-actions button{padding:8px 9px;border-radius:9px;border:1px solid #3b465d;background:#0d1725;color:#d0d5df;font-size:9px;font-weight:850;cursor:pointer}.ren-actions button.primary{border-color:#7f1d1d;background:#3a151d;color:#fecaca}.ren-actions button.success{border-color:#166534;background:#102b21;color:#bbf7d0}.ren-empty{padding:55px 20px;text-align:center;color:#858da0;font-size:12px}.ren-foot{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-top:14px;color:#697184;font-size:9px}.ren-foot b{color:#9ca4b5}
@media(max-width:1180px){.ren-work{grid-template-columns:1fr}.ren-kpis{grid-template-columns:repeat(2,1fr)}.ren-case{grid-template-columns:1.3fr 1fr .7fr .8fr}.ren-actions{grid-column:1/-1;justify-content:flex-start}}@media(max-width:760px){.ren-shell{padding:12px}.ren-top{align-items:flex-start;flex-direction:column}.ren-nav{width:100%;display:grid;grid-template-columns:1fr 1fr}.ren-nav a{text-align:center}.ren-hero{padding:20px;border-radius:22px}.ren-hero h1{font-size:36px}.ren-kpis{grid-template-columns:1fr 1fr}.ren-kpi{padding:14px}.ren-kpi strong{font-size:26px}.ren-toolbar .ren-input{max-width:none;width:100%}.ren-case{grid-template-columns:1fr}.ren-actions{justify-content:flex-start}}
</style>
@php($summary=$this->summary)
@php($rows=$this->rows)
<div class="ren-shell"><div class="ren-wrap">
<div class="ren-top"><div class="ren-brand"><div class="ren-logo">TPC</div><div><b>TPC Insurance OS</b><span>Doğuş Topçu Sigorta • Geri Kazanım Operasyonu</span></div></div><nav class="ren-nav"><a href="/admin/sigorta-operasyon">Operasyon Merkezi</a><a class="active" href="/admin/sigorta-yenileme">Geri Kazanım Merkezi</a></nav></div>
<section class="ren-hero"><div class="ren-eyebrow">Satış Geri Kazanım Motoru</div><h1>Kaçan poliçeyi görün. Müşteriyi yeniden kazanın.</h1><p>Mevcut poliçe portföyünü takip edin, başka yerde yenilendiği tespit edilen müşterileri ayrı satış kuyruğuna alın ve geri kazanım sonucunu ekip bazında yönetin.</p><span class="ren-badge">● Yetkili veri kaynağı bağlandığında otomatik tespit bu ekrana akacak</span></section>
<section class="ren-kpis"><article class="ren-kpi"><small>Takipte</small><strong>{{ $summary['monitoring'] }}</strong><span>Aktif portföy takibi</span></article><article class="ren-kpi"><small>Başka Yerde Yenilendi</small><strong>{{ $summary['detected'] }}</strong><span>Geri kazanım fırsatı</span></article><article class="ren-kpi"><small>Satış Ekibinde</small><strong>{{ $summary['assigned'] }}</strong><span>Aktif görüşme</span></article><article class="ren-kpi"><small>Geri Kazanıldı</small><strong>{{ $summary['recovered'] }}</strong><span>Tekrar kazanılan müşteri</span></article></section>
<div class="ren-work"><aside class="ren-card"><div class="ren-head"><h2>Portföy Takibi Ekle</h2><p>Yetkili otomatik veri kaynağı bağlanana kadar kayıtlar panelden veya içe aktarma ile eklenebilir.</p></div><form class="ren-form" wire:submit="createRecord"><div class="ren-field"><label>Müşteri</label><input class="ren-input" wire:model="customerName"></div><div class="ren-field"><label>Telefon</label><input class="ren-input" wire:model="phone"></div><div class="ren-field"><label>Plaka</label><input class="ren-input" wire:model="plate"></div><div class="ren-field"><label>Motor No</label><input class="ren-input" wire:model="motorNumber"></div><div class="ren-field"><label>Poliçe No</label><input class="ren-input" wire:model="policyNumber"></div><div class="ren-field"><label>Sigorta Şirketi</label><input class="ren-input" wire:model="insurer"></div><div class="ren-field"><label>Poliçe Bitiş Tarihi</label><input type="date" class="ren-input" wire:model="expiryDate"></div><button class="ren-btn" type="submit">Portföy Takibine Ekle</button></form></aside>
<section class="ren-card"><div class="ren-head"><h2>Geri Kazanım Kuyruğu</h2><p>Tespit edilen müşteriyi satış ekibine aktarın ve sonucu net biçimde kapatın.</p></div><div class="ren-toolbar"><input class="ren-input" wire:model.live.debounce.350ms="search" placeholder="Müşteri, plaka veya poliçe ara..."><div class="ren-filter">@foreach(['active'=>'Aktif','external_renewal_detected'=>'Tespit','assigned'=>'Satışta','recovered'=>'Kazanıldı','lost'=>'Kaybedildi','all'=>'Tümü'] as $key=>$label)<button type="button" class="{{ $filter===$key?'active':'' }}" wire:click="$set('filter','{{ $key }}')">{{ $label }}</button>@endforeach</div></div>
@if($rows->isEmpty())<div class="ren-empty">Henüz yenileme takip kaydı yok. Portföy verisi geldiğinde fırsatlar burada sıralanacak.</div>@else<div class="ren-list">@foreach($rows as $row)@php($cls=$row->status==='external_renewal_detected'?'detected':($row->status==='assigned'?'assigned':($row->status==='recovered'?'recovered':'')))<article class="ren-case" wire:key="ren-{{ $row->id }}"><div class="ren-main"><b>{{ $row->customer_name ?: 'Müşteri adı yok' }}</b><span>{{ $row->phone ?: 'Telefon yok' }}</span><span>{{ $row->policy_number ?: 'Poliçe no yok' }}</span></div><div class="ren-main"><b>{{ $row->plate ?: 'Plaka yok' }}</b><span>{{ $row->insurer ?: 'Sigorta şirketi yok' }}</span><span>Motor: {{ $row->motor_number ?: '—' }}</span></div><div class="ren-main"><b>{{ $row->expiry_date?->format('d.m.Y') ?: '—' }}</b><span>Poliçe bitişi</span></div><div><span class="ren-status {{ $cls }}">{{ $row->statusLabel() }}</span></div><div class="ren-actions">@if($row->status==='monitoring')<button class="primary" wire:click="markDetected({{ $row->id }})">Başka Yerde Yenilendi</button>@endif @if($row->status==='external_renewal_detected')<button wire:click="assignToSales({{ $row->id }})">Satışa Aktar</button>@endif @if(in_array($row->status,['external_renewal_detected','assigned']))<button class="success" wire:click="markRecovered({{ $row->id }})">Geri Kazanıldı</button><button wire:click="markLost({{ $row->id }})">Kaybedildi</button>@endif</div></article>@endforeach</div>@endif</section></div>
<div class="ren-foot"><span><b>TPC Insurance OS</b> • Doğuş Topçu Sigorta için özel geri kazanım merkezi</span><span>Yetkili veri entegrasyonu bağlandığında tespit akışı otomatikleşecektir.</span></div>
</div></div>
</x-filament-panels::page>
